In [1]:
import os

os.environ["HF_HOME"] = "/openbayes/home/huggingface"

# 理解token


In [2]:
# step1 加载模型

from transformers import AutoModelForCausalLM, AutoTokenizer

# 加载模型和tokenizer
model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2.5-0.5B-Instruct",
    device_map = "auto",
    torch_dtype = "auto",
    trust_remote_code = True,
)
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-0.5B-Instruct")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!


model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [3]:
prompt = "帮我写一个请假条，原因是自己生病了<|im_start|>assistant。"

# 使用tokenizer分词器将文本转换为PyTorch的张量格式，并提取出其中的input_ids，并把这个张量转移到当前模型所在的设备上
input_ids = tokenizer(prompt, return_tensors = "pt").input_ids.to(model.device)

# 调用模型，生成文本
generation_output = model.generate(
    input_ids = input_ids,
    max_new_tokens = 200
)

# 将生成的token序列解码成文字并输出
print(tokenizer.decode(generation_output[0]))
print("++++++++++++++++++++")
print(generation_output)

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


帮我写一个请假条，原因是自己生病了<|im_start|>assistant。 好的，以下是一个简单的请假条示例：

---

亲爱的 [同事/上司的名字],

我由于身体原因需要请假三天，以便照顾好我的家人和朋友。

请在 [截止日期]前回复，我会尽快补齐相关工作并恢复到正常状态。

谢谢！

[你的名字]
[你的职位]
[联系电话]

---

请注意根据实际情况调整细节，并确保所有信息准确无误。希望这个请假条对你有所帮助！<|im_end|>
++++++++++++++++++++
tensor([[108965,  61443,  46944, 118962,  38989,   3837, 107711,  99283, 109281,
          34187, 151644,  77091,   1773,   4891,     98,    121,   9370,   3837,
          87752, 101909, 105172, 118962,  38989,  19793,  26355,  48443,  44364,
         110834,    508, 102454,     14, 116457, 105180,  49088,  35946, 101887,
         101099,  99917,  85106, 118962, 106635,   3837, 105920, 104987,  52801,
          97611, 104271,  33108,  99614,   3407,  14880,  18493,    508, 105974,
          45785,     60,  24562, 104787,   3837, 105351, 104883, 117698,  78556,
          99257,  62926, 102005,  26939, 100416,  44091,   3407, 102570,  17701,
             58, 103929, 101419,    921,     58, 103929, 106664,    921,     58,
         112215,   2533

| 特性   | `tokenizer.decode()` | `tokenizer.batch_decode()`            |
| ---- | -------------------- | ------------------------------------- |
| 输入   | 单个 token ID 序列（1D）   | 多个 token ID 序列（2D）                    |
| 输出   | 单个字符串                | 字符串列表（每条对应一个序列）                       |
| 常见用途 | 解码一条输出               | 解码多个批次生成结果                            |
| 示例输入 | `[101, 2035, 102]`   | `[[101, 2035, 102], [101, 999, 102]]` |
| 示例输出 | `"这是文本"`             | `["这是文本", "另一条文本"]`                   |


In [4]:
print(input_ids)

tensor([[108965,  61443,  46944, 118962,  38989,   3837, 107711,  99283, 109281,
          34187, 151644,  77091,   1773]])


In [6]:
for id in input_ids[0]:
    print(tokenizer.decode(id))

帮我
写
一个
请假
条
，
原因是
自己
生病
了
<|im_start|>
assistant
。


In [10]:
from transformers import AutoModelForCausalLM,AutoTokenizer

# 定义颜色列表
colors_list = [
    '102;194;165', '252;141;98', '141;160;203',
    '231;138;195', '166;216;84', '255;217;47'
]

# 定义show_tokens函数
def show_tokens(sentence, tokenizer_name):
    # 从指定的模型名称加载对应的分词器
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
    # 将句子编码成token id列表
    token_ids = tokenizer(sentence).input_ids
    # 循环打印token
    for idx, t in enumerate(token_ids):
        print(
            f'\x1b[0;30;48;2;{colors_list[idx % len(colors_list)]}m' +
            tokenizer.decode(t) +
            '\x1b[0m',
            end=' '    
        )

# 测试文本
text = """
English and CAPITALIZATION
🎵 鸟
show_tokens False None elif == >= else: two tabs:"    " Three tabs: "       "
12.0*50=600
"""


In [12]:
show_tokens(text, "bert-base-uncased")

[CLS] english and capital ##ization [UNK] [UNK] show _ token ##s false none eli ##f = = > = else : two tab ##s : " " three tab ##s : " " 12 . 0 * 50 = 600 [SEP] 

In [13]:
show_tokens(text, "gpt2")

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]


 English  and  CAP ITAL IZ ATION 
 � � �  � � � 
 show _ t ok ens  False  None  el if  ==  >=  else :  two  tabs :"        "  Three  tabs :  "              " 
 12 . 0 * 50 = 600 
 

In [14]:
show_tokens(text,"Qwen/Qwen2.5-0.5B-Instruct")


 English  and  CAPITAL IZATION 
 🎵  � � � 
 show _tokens  False  None  elif  ==  >=  else :  two  tabs :"      "  Three  tabs :  "         "
 1 2 . 0 * 5 0 = 6 0 0 
 

# 理解Embedding

In [3]:
pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 68.1 MB/s eta 0:00:00:00:0100:01


In [4]:
# 原始embedding(和LLM无关)
## GloVe (Global Vectors):由standford提出的一种词向量训练方法
import gensim.downloader as api

# 下载并加载模型
model = api.load("glove-wiki-gigaword-50")

# 获取与king最相似的词
model.most_similar([model["king"]],topn=11)

[==================================================] 100.0% 66.0/66.0MB downloaded


[('king', 1.0000001192092896),
 ('prince', 0.8236179351806641),
 ('queen', 0.7839043140411377),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247777938843),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542161345481873),
 ('throne', 0.7539914846420288),
 ('brother', 0.7492411136627197),
 ('ruler', 0.7434253692626953)]

In [5]:
# 上下文相关的embeddng
from transformers import AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

model = AutoModel.from_pretrained("bert-base-uncased")

# 将字符串 Hello world 编码成可用的张良形式
tokens = tokenizer("Hello world", return_tensors="pt")

# 将上面的 tokens 输入给模型，得到模型的输出。output 是一个张量，表示每个 token 的隐藏状态（embedding）：
output = model(**tokens)[0]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [6]:
output

tensor([[[-0.1689,  0.1361, -0.1394,  ..., -0.6251,  0.0522,  0.3671],
         [-0.3633,  0.1412,  0.8800,  ...,  0.1043,  0.2888,  0.3727],
         [-0.6986, -0.6988,  0.0645,  ..., -0.2210,  0.0099, -0.5940],
         [ 0.8310,  0.1237, -0.1512,  ...,  0.1031, -0.6779, -0.2629]]],
       grad_fn=<NativeLayerNormBackward0>)

In [7]:
for token in tokens['input_ids'][0]:
    print(tokenizer.decode(token))

[CLS]
hello
world
[SEP]


In [8]:
# 文本向量

# 引入SentenceTransformer类，这是sentence_transformers库的核心类，用于加载预训练的文本嵌入模型
from sentence_transformers import SentenceTransformer

# 加载一个已经训练好的句子级别的嵌入模型
model = SentenceTransformer('sentence-transformers/all-distilroberta-v1')

# 将文本编码成一个固定维度的向量
vector = model.encode("测试一个小模型的embedding能力")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/653 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/328M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/333 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [25]:
vector

array([-1.14205210e-02, -4.36423644e-02,  1.91101134e-02,  1.98334958e-02,
       -2.85172276e-02, -8.38975422e-03, -3.92199382e-02,  7.88183231e-03,
       -3.17559950e-02, -4.14471179e-02, -1.62048060e-02,  2.02986673e-02,
       -1.03204893e-02, -1.13158897e-02, -4.32766005e-02,  2.13359878e-03,
        8.14641938e-02, -1.50566269e-02, -1.28567163e-02,  9.15836394e-02,
        2.48903632e-02,  4.28533973e-03, -2.26561371e-02, -8.71132836e-02,
       -5.67577705e-02, -2.09845714e-02,  2.80383788e-02, -3.68181057e-02,
       -6.90571293e-02, -3.50757912e-02, -2.93971337e-02,  4.33225445e-02,
        2.13696938e-02, -8.26139119e-04,  1.04102362e-02, -1.75086688e-02,
        1.02887578e-01, -3.07366103e-02,  2.81132460e-02,  2.39831265e-02,
       -4.96314168e-02,  5.90494201e-02,  3.65481898e-02, -4.64874730e-02,
        3.94217633e-02,  2.87421956e-03, -4.73062545e-02, -8.65442157e-02,
       -9.92390607e-03,  3.23161967e-02,  4.79928888e-02,  2.72446908e-02,
       -4.67069149e-02,  

In [9]:
# 查看embedding的向量维度
vector.shape

(768,)

In [ ]:
# 基于 embeddings 的歌曲推理
import pandas as pd
# 用于从网络上下载文件或网页内容
from urllib import request

# 打开一个url链接，读取远程服务器上名为train.txt的数据文件
data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')

# 读取文件，将字节数据解码成字符串，然后按行将整个文本分割成一个字符串列表。并跳过前两行
lines = data.read().decode('utf-8').split('\n')[2:]

# 对每一行进行处理，去除结尾的空白字符，按空格分割成一个字符串列表：每个元素是一个播放列表（含多首歌），以歌曲 ID 形式存储的字符串数。并过滤掉只有 1 首歌的播放列表（不利于训练 Word2Vec）。
playlists = [s.rstrip().split() for s in lines if len(s.split()) > 1]

# 加载歌曲元数据
songs_file = request.urlopen("https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt")
songs_file = songs_file.read().decode("utf-8").split("\n")
songs = [s.rstrip().split('\t') for s in songs_file]

# 将songs列表转换成pandas.DataFrame，每一行是一首歌
songs_df = pd.DataFrame(data=songs, columns = ['id','title','artist'])
# 设置索引列
songs_df = songs_df.set_index('id')

In [12]:
print("PlayList #1:\n", playlists[0],'\n')
print("Playlist #2:\n", playlists[1])

PlayList #1:
 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '2', '42', '43', '44', '45', '46', '47', '48', '20', '49', '8', '50', '51', '52', '53', '54', '55', '56', '57', '25', '58', '59', '60', '61', '62', '3', '63', '64', '65', '66', '46', '47', '67', '2', '48', '68', '69', '70', '57', '50', '71', '72', '53', '73', '25', '74', '59', '20', '46', '75', '76', '77', '59', '20', '43'] 

Playlist #2:
 ['78', '79', '80', '3', '62', '81', '14', '82', '48', '83', '84', '17', '85', '86', '87', '88', '74', '89', '90', '91', '4', '73', '62', '92', '17', '53', '59', '93', '94', '51', '50', '27', '95', '48', '96', '97', '98', '99', '100', '57', '101', '102', '25', '103', '3', '104', '105', '106', '107', '47', '108', '109', '110', '111', '112', '113', '25', '63', '62', '114', '115', '84', '116', '117', '

In [16]:
print('songs_df #1:\n',songs_df)

songs_df #1:
            id                                              title  \
0          0                        Gucci Time (w\/ Swizz Beatz)   
1          1   Aston Martin Music (w\/ Drake & Chrisette Mich...   
2          2                       Get Back Up (w\/ Chris Brown)   
3          3                  Hot Toddy (w\/ Jay-Z & Ester Dean)   
4          4                                        Whip My Hair   
...       ...                                                ...   
75258  75258                                           USA Today   
75259  75259                                           Superstar   
75260  75260                                 Romancin' The Blues   
75261  75261                                        Inner Change   
75262                                                       None   

                artist  
0           Gucci Mane  
1            Rick Ross  
2                 T.I.  
3                Usher  
4               Willow  
...                

In [17]:
# 导入woed2evc模型类，用于训练词向量
from gensim.models import Word2Vec

# 使用哟关于播放列表（playlist）数据来训练Word2Vec模型
model = Word2Vec(
    playlists, # 输入数据
    vector_size = 32, # 每个词向量会被编码为一个32维的向量
    window = 20, # 训练时，模型会在一个窗口大小为20的范围内寻找上下文词
    negative = 50 , # 负采样数量。每个正样本会配合50个负样本进行训练。负样本用于提高训练效率
    min_count = 1, # 只要某个token出现至少1次就会被考虑进训练数据中
    workers = 4, # 使用4个线程进行并行训练，加快速度
)

In [18]:
# 想要查询的目标歌曲ID
song_id = 2172
# mode.wv:访问word2evc模型中训练好的词向量
# most_similar:在词向量空间中，找到与给定向量最相近的向量（通过余弦相似度cosine similarity计算）
# 注意：word2evc的most_similar需要输入词（token），而playists中的每首歌是一个字符串，因此需要将song_id转为字符串类型的
model.wv.most_similar(positive=str(song_id))

[('2849', 0.9988282322883606),
 ('2715', 0.99770587682724),
 ('2886', 0.9976075887680054),
 ('6624', 0.9972023963928223),
 ('2640', 0.9970270991325378),
 ('3167', 0.9969965219497681),
 ('2987', 0.9965242743492126),
 ('2704', 0.9965136051177979),
 ('2976', 0.9963898062705994),
 ('3094', 0.9963487982749939)]

In [19]:
songs_df.iloc[2171]

id            2171 
title     Vicarious
artist         Tool
Name: 2171, dtype: object

In [21]:
import numpy as np

# 定义推荐函数
def print_recommendations(song_id):
    similar_songs = np.array(
        model.wv.most_similar(positive = str(song_id),topn=5)
    )[:,0]
    return songs_df.iloc[similar_songs]

print_recommendations(2171)

id                 title            artist
1880    1880          Forty Six & 2              Tool
5491    5491   Animal I Have Become  Three Days Grace
14579  14579             Let It Die      Foo Fighters
5541    5541                  Awake          Godsmack
17964  17964                 Psycho    Puddle Of Mudd

In [22]:
print(songs_df.iloc[842])

print_recommendations(842)

id                                                  842 
title     California Love (w\/ Dr. Dre & Roger Troutman)
artist                                              2Pac
Name: 842, dtype: object


id                                              title  \
413      413   If I Ruled The World (Imagine That) (w\/ Laury...   
27081  27081    Give Me Everything (w\/ Ne-Yo, Afrojack & Nayer)   
196      196                                 I'll Be Missing You   
5839    5839                                        Bring Em Out   
12205  12205                                    Give It Up To Me   

                        artist  
413                        Nas  
27081                  Pitbull  
196    Puff Daddy & The Family  
5839                      T.I.  
12205                Sean Paul